
# borders
default_border pixel 2
default_floating_border pixel 2

# gaps
gaps inner 8
gaps outer 0
smart_gaps off

# colors <border_color> <background_color> <text_color> <indicator_color=the_bug_border> <child_border_color=rest_of_border>
client.focused #a9b1d6 #a9b1d6 #000000 #a9b1d6 #a9b1d6
client.focused_inactive #1a1b26 #1a1b26 #a9b1d6 #1a1b26 #1a1b26
client.unfocused #a9b1d6 #1a1b26 #a9b1d6 #1a1b26 #1a1b26

