#!/usr/bin/env python3

import subprocess
import os
from typing import List, Union, Callable

note_icon = " Add note"
todo_icon = "󰄲 Add Todo"
read_icon = "󰂺 Notebook"

def main_menu() -> str:
    options: List[str] = [
        note_icon,
        todo_icon,
        read_icon,
    ]

    menu = "\n".join(options)

    result = subprocess.run(
        [
            "rofi",
            "-dmenu",
            "-theme", os.path.expanduser("~/.config/rofi/styles/notes.rasi"),
        ],
        input=menu,
        capture_output=True,
        text=True,
    ).stdout.strip()

    return result


def run_cmd(cmd: List[str]):
    subprocess.run(cmd)


def power():
    selected = main_menu()

    action_map: dict[str, Union[Callable, List[str]]] = {
        note_icon: [os.path.expanduser("~/.config/fuzzel/scripts/daily-note.sh")],
        read_icon: ["foot", "bash", "-ic", "notes"],
        todo_icon: [os.path.expanduser("~/.config/fuzzel/scripts/todo.sh")],
    }

    action = action_map.get(selected)

    if not action:
        return

    if callable(action):
        action()
    else:
        run_cmd(action)


if __name__ == "__main__":
    power()
