#font=JetBrains Mono Nerd Font:weight=regular:size=11
font=Caskaydia Mono Nerd Font:weight=regular:size=11
gamma-correct=yes
prompt="→ "
icons-enabled=no
icon-theme=Papirus-Dark
fields=name,generic,comment,categories,filename,keywords
show-actions=no
lines=10
width=45
horizontal-pad=20
vertical-pad=12
inner-pad=8
layer=overlay
exit-on-keyboard-focus-loss=yes

[colors]
background=1a1b26ff
text=a9b1d6ff
input=a9b1d6ff
match=bf616aff
selection=252736ff
selection-text=bf616aff
selection-match=bf616aff
border=88c0d0ff
prompt=88c0d0ff

[border]
width=2
radius=16
