
# floating windows
for_window [class="Rofi"] floating enable

# assigned workspaces
assign [app_id="brave-browser"] 2
assign [app_id="brave-origin"] 2
assign [app_id="com.ktechpit.whatsie"] 3
assign [app_id="spotify"] 3
