set $laptop eDP-1
bindswitch --reload --locked lid:on output $laptop disable
bindswitch --reload --locked lid:off output $laptop enable
exec_always ./lid-state.sh

output HDMI-A-2 resolution 2560x1440 scale 1
#swaymsg -t get_outputs
